apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-release-secrets
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/motrabelsi10/med.git'
    path: mychart
    targetRevision: main
    helm:
      valueFiles:
        - secrets.yaml
      releaseName: my-release
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  revisionHistoryLimit: 10
