apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://github.com/argoproj/argo-cd/manifests/cluster-install?ref=v2.8.4
patchesStrategicMerge:
  - argocd-notification-cm.yaml
  - argocd-notification-secret.yaml
namespace: mynamespace