name: Build & Deploy Myapp

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build And Deploy MyApp
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/med:v${{ github.run_number }}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/med:v${{ github.run_number }}

      - name: Update image tags in values.yaml
        run: |
          TAG=v${{ github.run_number }}
          sed -i "s/^ *tag: \"v[0-9]*\"$/  tag: \"$TAG\"/" mychart/values.yaml


      - name: Commit and push changes to repository
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          git config user.email "trabelsi.mohamed.1@esprit.tn"
          git config user.name "motrabelsi10"
          git add mychart/values.yaml
          git commit -m "Update image tag"
          git push origin main

      - name: Install Minikube dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y apt-transport-https ca-certificates curl conntrack
          sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
          sudo apt-get update -y
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io

      - name: Install crictl
        run: |
          VERSION="v1.22.0"
          curl -LO https://github.com/kubernetes-sigs/cri-tools/releases/download/$VERSION/crictl-$VERSION-linux-amd64.tar.gz
          sudo tar -C /usr/local/bin -xzf crictl-$VERSION-linux-amd64.tar.gz
          rm -f crictl-$VERSION-linux-amd64.tar.gz

      - name: Install Minikube
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube

      - name: Start Minikube
        run: |
          sudo minikube start --driver=none
          sudo minikube status

      - name: Install kubectl
        run: |
          curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Upgrade Helm release
        run: |
          helm upgrade my-release mychart --namespace mynamespace