name: Build & Deploy Myapp

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build And Deploy MyApp
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/testpipeline:v${{ github.run_number }}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/testpipeline:v${{ github.run_number }}

      - name: Update image tag in values.yaml
        run: |
          TAG=${{ github.sha }}
          sed -i "s/tag: .*/tag: \"$TAG\"/" mychart/values.yaml

      - name: Commit and push changes to repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.email "trabelsi.mohamed.1@esprit.tn"
          git config user.name "motrabelsi10"
          git add mychart/values.yaml
          git commit -m "Update image tag to ${{ github.sha }}"
          git push origin main
